import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Image from "next/image";
import LogoB from "../../../public/img/LOGO_FULL_BRANCO.png";
import Brasao from "../../../public/img/BRASAO_CINZA.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Antecipação Saque aniversário FGTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#1242cf" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2&family=Dongle:wght@300&family=Gochi+Hand&family=Poppins&family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
        <script src="https://kit.fontawesome.com/8d9284e27b.js" crossOrigin="anonymous" async></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      </Head>

      <main className="bg-slate-50 poppins">
        <div className="grid grid-cols-1 lg:grid-cols-3">
          <div className="col-span-1 lg:h-[97.8vh] bg-[#1242cf] m-2 rounded-xl">
            <div className="p-5">
              <Image src={LogoB} width={150} height={32.99} />
            </div>
          </div>

          <div className="col-span-1 lg:col-span-2 h-screen text-slate-400">
            <div className="p-5">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro
              nulla exercitationem voluptas quam commodi officiis? Molestias,
              veritatis quia! Tempora sequi perspiciatis tenetur ipsam
              molestias. Praesentium magni minima hic eius quidem! Lorem ipsum
              dolor sit amet consectetur adipisicing elit. Porro nulla
              exercitationem voluptas quam commodi officiis? Molestias,
              veritatis quia! Tempora sequi perspiciatis tenetur ipsam
              molestias. Praesentium magni minima hic eius quidem! Lorem ipsum
              dolor sit amet consectetur adipisicing elit. Porro nulla
              exercitationem voluptas quam commodi officiis? Molestias,
              veritatis quia! Tempora sequi perspiciatis tenetur ipsam
              molestias. Praesentium magni minima hic eius quidem!
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
