import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Image from "next/image";
import LogoB from "../../../public/img/LOGO_FULL_BRANCO.png";
import Brasao from "../../../public/img/BRASAO_CINZA.png";
import StepUm from "../../../components/FORM/StepFGTS1"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Antecipação Saque aniversário FGTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#1242cf" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2&family=Dongle:wght@300&family=Gochi+Hand&family=Poppins&family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
        <script src="https://kit.fontawesome.com/8d9284e27b.js" crossOrigin="anonymous" async></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      </Head>

      <main className="bg-slate-50 poppins">

        <div className="grid grid-cols-1 lg:grid-cols-5">
          
          <div className="m-2 col-span-2 lg:h-[97.5vh] bg-gradient-to-br from-blue-600 via-blue-700 to-blue-700 saturate-150 rounded-xl">
            <div className="p-5">
              <Image src={LogoB} width={110} height={24.19} />
            </div>
          </div>

          <div className="col-span-1 lg:col-span-3 text-slate-400 lg:pr-64 lg:pl-16 h-screen">
            <div className="p-5">
              <StepUm/>
            </div>
          </div>

        </div>
      
      </main>

    </div>
  );
}
