export const cliente = {
    primeiroNome: "Thiago",
  	nomeCompleto: "Thiago Bronisio Damascena",
  	iniciais: "TD",
  	cpf: "152.891.967-06",
  	nascimento: "25/06/2001",
  	rg: "30.08.0488.48",
	mae: "Edilene Amorim Bronisio",
	email: "Thiagobronisioo@gmail.com",
	celular: "(21) 96584-6290",
	endereco: "Rua das Palmeiras, 120 - Rio de Janeiro, RJ",
	banco: "Nu Pagamentos S.A.",
	completude: 82,
};

//Propostas em analise
export const modalidadesCredito = [

	//FGTS
	{
		id: "fgts",
		nome: "Saque FGTS",
		descricao: "Antecipacao do saque-aniversario disponivel no FGTS.",
		proposta: {
			id: "012026",
			modalidade: "Saque FGTS",
			etapaAtual: "Consulta em andamento",
			status: "Pendente dados de contato",
			tipoStatus: "pendente",
			descricaoStatus: "A analise ja foi iniciada, mas precisamos confirmar os dados de contato antes de liberar a formalizacao. Resolva a pendencia para a proposta seguir no fluxo.",
			valor: "R$ 4.280,00",
			numero: "012026",
			progresso: 64,
			instituicaoFinanceira: "Banco PAN",
			taxaJuros: "1,79% a.m.",
			iof: "R$ 86,40",
			consultor: "Mariana Lopes",
			prioridade: "Alta",
			proximaAcao: "Aguardando validacao dos documentos enviados.",
			dadosProposta: [
				{ rotulo: "Valor solicitado", valor: "R$ 4.280,00", destaque: true },
				{ rotulo: "Prazo", valor: "10 parcelas" },
				{ rotulo: "Parcela", valor: "Desconto anual FGTS" },
				{ rotulo: "Saldo devedor", valor: "Nao se aplica" },
			],
			pendencia: {
				titulo: "Confirmar dados de contato",
				descricao: "Precisamos confirmar celular e e-mail para liberar a formalizacao assim que a analise for concluida.",
				cta: "Resolver pendencia",
			},
			etapas: [
				{
					titulo: "Cadastro recebido",
					descricao: "Dados enviados com sucesso",
					estado: "done",
					data: "03/07/2026",
					horario: "09:12",
				},
				{
					titulo: "Consulta em andamento",
					descricao: "Estamos conferindo elegibilidade e margem",
					estado: "current",
					data: "03/07/2026",
					horario: "10:35",
				},
				{
					titulo: "Formalizacao",
					descricao: "Liberada apos aprovacao da proposta",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
				{
					titulo: "Pagamento",
					descricao: "Credito na conta informada",
					estado: "waiting",
					data: "A definir",
					horario: "Final",
				},
			],
			destaque: true,
		},
	},
  
	{
		id: "credluz",
		nome: "CredLuz",
		descricao: "Credito com validacao pela conta de energia.",
		proposta: {
			id: "012027",
			modalidade: "CredLuz",
			etapaAtual: "Confirmacao da titularidade",
			status: "Em analise",
			tipoStatus: "analise",
			descricaoStatus: "Estamos verificando se a conta de energia informada atende aos criterios da modalidade e se os dados do titular batem com o cadastro.",
			valor: "R$ 1.850,00",
			numero: "012027",
			progresso: 46,
			instituicaoFinanceira: "Crefaz",
			taxaJuros: "2,49% a.m.",
			iof: "R$ 41,20",
			consultor: "Rafael Costa",
			prioridade: "Normal",
			proximaAcao: "Aguardando retorno da validacao da concessionaria.",
			dadosProposta: [
				{ rotulo: "Valor solicitado", valor: "R$ 1.850,00", destaque: true },
				{ rotulo: "Prazo", valor: "18 parcelas" },
				{ rotulo: "Parcela", valor: "R$ 156,40" },
				{ rotulo: "Saldo devedor", valor: "Nao se aplica" },
			],
			pendencia: null,
			etapas: [
				{
					titulo: "Cadastro recebido",
					descricao: "Solicitacao criada no CRM",
					estado: "done",
					data: "03/07/2026",
					horario: "11:20",
				},
				{
					titulo: "Titularidade",
					descricao: "Conferindo dados da fatura",
					estado: "current",
					data: "03/07/2026",
					horario: "11:42",
				},
				{
					titulo: "Proposta",
					descricao: "Condicoes liberadas apos validacao",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
			],
			destaque: false,
    	},
  	},

	{
		id: "consignado-clt",
		nome: "Consignado CLT",
		descricao: "Credito consignado para trabalhador com vinculo CLT.",
		proposta: {
			id: "012028",
			modalidade: "Consignado CLT",
			etapaAtual: "Retorno da analise",
			status: "Recusado por margem",
			tipoStatus: "recusado",
			descricaoStatus: "A proposta foi recusada porque a margem disponivel retornada na analise nao comporta a parcela simulada. O cliente pode consultar novas condicoes quando houver margem disponivel.",
			valor: "R$ 6.500,00",
			numero: "012028",
			progresso: 55,
			instituicaoFinanceira: "Facta Financeira",
			taxaJuros: "1,92% a.m.",
			iof: "R$ 132,70",
			consultor: "Mariana Lopes",
			prioridade: "Normal",
			proximaAcao: "Aguardando integracao com a base do empregador.",
			dadosProposta: [
				{ rotulo: "Valor solicitado", valor: "R$ 6.500,00", destaque: true },
				{ rotulo: "Prazo", valor: "24 parcelas" },
				{ rotulo: "Parcela", valor: "R$ 398,70" },
				{ rotulo: "Saldo devedor", valor: "Nao se aplica" },
			],
			pendencia: null,
			etapas: [
				{
					titulo: "Cadastro",
					descricao: "Dados basicos recebidos",
					estado: "done",
					data: "02/07/2026",
					horario: "16:10",
				},
				{
					titulo: "Vinculo CLT",
					descricao: "Confirmacao do empregador",
					estado: "done",
					data: "03/07/2026",
					horario: "09:05",
				},
				{
					titulo: "Margem",
					descricao: "Margem insuficiente",
					estado: "current",
					data: "03/07/2026",
					horario: "09:48",
				},
				{
					titulo: "Oferta",
					descricao: "Apresentacao das condicoes",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
				{
					titulo: "Formalizacao",
					descricao: "Assinatura digital",
					estado: "waiting",
					data: "A definir",
					horario: "Final",
				},
			],
			destaque: false,
		},
  	},

  	{
		id: "consignado-inss",
		nome: "Consignado INSS",
		descricao: "Credito consignado para aposentados e pensionistas.",
		proposta: null,
  	},

  	{
		
		id: "refin-auto",
		nome: "Refin de veiculo",
		descricao: "Credito com garantia de veiculo e quitacao do saldo atual.",
		proposta: {
			id: "012029",
			modalidade: "Refin de veiculo",
			etapaAtual: "Vistoria e saldo devedor",
			status: "Pendente CRLV",
			tipoStatus: "pendente",
			descricaoStatus: "A analise da garantia precisa do CRLV atualizado para confirmar os dados do veiculo, o saldo devedor e o valor liquido que pode ser liberado.",
			valor: "R$ 18.000,00",
			numero: "012029",
			progresso: 58,
			instituicaoFinanceira: "Santander Financiamentos",
			taxaJuros: "1,49% a.m.",
			iof: "R$ 388,10",
			consultor: "Rafael Costa",
			prioridade: "Normal",
			proximaAcao: "Aguardando retorno da vistoria e da instituicao credora atual.",
			dadosProposta: [
				{ rotulo: "Valor solicitado", valor: "R$ 18.000,00", destaque: true },
				{ rotulo: "Prazo", valor: "36 parcelas" },
				{ rotulo: "Parcela", valor: "R$ 724,80" },
				{ rotulo: "Saldo devedor", valor: "R$ 9.420,00" },
				{ rotulo: "Liquido estimado", valor: "R$ 8.580,00" },
				{ rotulo: "Bruto da operacao", valor: "R$ 18.000,00" },
			],
			pendencia: {
				titulo: "Enviar documento do veiculo",
				descricao: "Precisamos do CRLV atualizado para concluir a analise da garantia e confirmar o saldo devedor.",
				cta: "Enviar documento",
			},
			etapas: [
				{
					titulo: "Cadastro",
					descricao: "Dados e placa recebidos",
					estado: "done",
					data: "02/07/2026",
					horario: "14:18",
				},
				{
					titulo: "Vistoria",
					descricao: "Validacao do veiculo",
					estado: "current",
					data: "03/07/2026",
					horario: "12:08",
				},
				{
					titulo: "Saldo devedor",
					descricao: "Consulta da divida atual",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
				{
					titulo: "Oferta",
					descricao: "Calculo de bruto e liquido",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
				{
					titulo: "Formalizacao",
					descricao: "Assinatura do contrato",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
				{
					titulo: "Pagamento",
					descricao: "Quitacao e liberacao",
					estado: "waiting",
					data: "A definir",
					horario: "Final",
				},
			],
			destaque: true,
		},
  	},
  
	{
		id: "pix-parcelado",
		nome: "PIX Parcelado",
		descricao: "Credito rapido via PIX, com pagamento parcelado.",
		proposta: {
			id: "012030",
			modalidade: "PIX Parcelado",
			etapaAtual: "Validacao do limite",
			status: "Aguardando autorizacao",
			tipoStatus: "aguardando",
			descricaoStatus: "A proposta esta aguardando a autorizacao do meio de pagamento para confirmar o limite disponivel e liberar a formalizacao do PIX Parcelado.",
			valor: "R$ 2.400,00",
			numero: "012030",
			progresso: 42,
			instituicaoFinanceira: "BMP Money Plus",
			taxaJuros: "3,29% a.m.",
			iof: "R$ 58,90",
			consultor: "Mariana Lopes",
			prioridade: "Normal",
			proximaAcao: "Aguardando validacao do limite disponivel.",
			dadosProposta: [
				{ rotulo: "Valor solicitado", valor: "R$ 2.400,00", destaque: true },
				{ rotulo: "Prazo", valor: "12 parcelas" },
				{ rotulo: "Parcela", valor: "R$ 268,90" },
				{ rotulo: "Saldo devedor", valor: "Nao se aplica" },
			],
			pendencia: null,
			etapas: [
				{
					titulo: "Cadastro recebido",
					descricao: "Dados enviados para simulacao",
					estado: "done",
					data: "01/07/2026",
					horario: "15:32",
				},
				{
					titulo: "Simulacao",
					descricao: "Condicoes calculadas",
					estado: "done",
					data: "02/07/2026",
					horario: "09:44",
				},
				{
					titulo: "Validacao do limite",
					descricao: "Aguardando autorizacao",
					estado: "current",
					data: "03/07/2026",
					horario: "13:12",
				},
				{
					titulo: "Formalizacao",
					descricao: "Confirmacao das parcelas",
					estado: "waiting",
					data: "A definir",
					horario: "Proxima etapa",
				},
				{
					titulo: "PIX",
					descricao: "Credito na chave informada",
					estado: "waiting",
					data: "A definir",
					horario: "Final",
				},
			],
			destaque: false,
		},
	},
];

export const propostasEmAnalise = modalidadesCredito
  	.filter((modalidade) => Boolean(modalidade.proposta))
		.map((modalidade) => ({...modalidade.proposta, modalidade : modalidade.proposta.modalidade || modalidade.nome,}
	)
);

export const propostas = propostasEmAnalise.map((proposta) => ({
	id: proposta.numero,
	produto: proposta.modalidade,
	descricao: proposta.descricaoStatus,
	valor: proposta.valor,
	status: proposta.status,
	etapa: proposta.etapaAtual,
	vencimento: proposta.proximaAcao,
	progresso: proposta.progresso,
	tipoStatus: proposta.tipoStatus,
	destaque: proposta.tipoStatus === "pendente" || Boolean(proposta.pendencia),
}));

export const contratosRealizados = [
  	{
		id: "CTR-8801",
		produto: "Consignado CLT",
		descricao: "Credito contratado",
		valor: "R$ 6.500,00",
		status: "Contrato realizado",
		etapa: "Pagamento concluido",
		vencimento: "Finalizado em 12/06/2026",
		progresso: 100,
		destaque: false,
  	},

  	{
		id: "CTR-7950",
		produto: "Conta digital",
		descricao: "Atualizacao cadastral validada",
		valor: "Sem custo",
		status: "Contrato realizado",
		etapa: "Dados conferidos",
		vencimento: "Finalizado em 21/05/2026",
		progresso: 100,
		destaque: false,
  	},
];

export const ofertas = [
  	{
		id: "credito-com-energia",
		titulo: "Credito com energia",
		descricao: "Oferta pre-validada usando sua fatura como referencia.",
		etiqueta: "Rapido",
		valor: "ate R$ 2.000",
		cor: "blue",
  	},
  	{
		id: "refin-veiculo",
		titulo: "Refin de veiculo",
		descricao: "Simule usando o veiculo para melhorar as condicoes.",
		etiqueta: "Taxa menor",
		valor: "a partir de 1,49%",
		cor: "yellow",
  	},
  	{
		id: "consignado-clt",
		titulo: "Consignado CLT",
		descricao: "Possibilidade de parcelas com desconto em folha.",
		etiqueta: "Novo",
		valor: "analise gratis",
		cor: "green",
  	},
];

export const dadosPerfil = [
	{ rotulo: "Nome", valor: cliente.nomeCompleto },
	{ rotulo: "CPF", valor: cliente.cpf },
	{ rotulo: "Nascimento", valor: cliente.nascimento },
	{ rotulo: "RG", valor: cliente.rg },
	{ rotulo: "Nome da mae", valor: cliente.mae },
	{ rotulo: "Email", valor: cliente.email },
	{ rotulo: "Celular", valor: cliente.celular },
];

export const acoesPerfil = [
	{
		titulo: "Endereco",
		descricao: cliente.endereco,
		status: "Atualizado",
	},
	{
		titulo: "Dados bancarios",
		descricao: cliente.banco,
		status: "Conferir",
	},
	{
		titulo: "Senha e seguranca",
		descricao: "Ultima atualizacao ha 38 dias",
		status: "Recomendado",
	},
	{
		titulo: "Privacidade",
		descricao: "Termos, consentimentos e comunicacoes",
		status: "Ver",
	},
];
