import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import IndexCREDLUZ from '../../components/CREDLUZ/IndexCREDLUZ'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Empréstimo na conta de luz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2&family=Dongle:wght@300&family=Gochi+Hand&family=Poppins:wght@100;200;300;400;500;600;700;800&family=Ubuntu:wght@300&display=swap" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/8d9284e27b.js" crossOrigin="anonymous" async></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      </Head>
      <IndexCREDLUZ />
    </div>
  )
}
