import Head from "next/head";
import styles from "../../../styles/Home.module.css";
import Image from "next/image";
import LogoB from "../../../public/img/LOGO_FULL_BRANCO.png";


export default function Home() {
  return (
    
    <div className={styles.container}>
        
        <Head>
            <title>Resultado da Pré-Análise</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="theme-color" content="#1242cf" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=Baloo+2&family=Dongle:wght@300&family=Gochi+Hand&family=Poppins&family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
            <script src="https://kit.fontawesome.com/8d9284e27b.js" crossOrigin="anonymous" async></script>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
        </Head>

        <main className="bg-slate-50 poppins">
            
            <div className="grid grid-cols-1 lg:grid-cols-5 h-[100vh]">

                <div className="m-2 h-24 lg:h-[97.5vh] col-span-2 bg-gradient-to-br from-blue-800 via-blue-700 to-blue-600 rounded-xl">
                    <div className="p-8 flex justify-end">
                        <Image src={LogoB} width={130} alt='' />
                    </div>
                </div>

                <div className="col-span-1 lg:col-span-3 text-slate-400 lg:max-w-3xl lg:px-10 mt-8">
                    <div className="">
                       
                    </div>
                </div>

            </div>

        </main>

    </div>
  );
}
