import Head from 'next/head'
import IndexCP from '../../components/CP/IndexCP'
import { Poppins } from 'next/font/google'

const mainFontFamily = Poppins({
    weight: ['100','200','300','400','500','600','700','800','900'],
    subsets: ['latin']
});

export default function Home() {
  return (
    <div>
        <Head>
            <title>Valoreal Crédito Online</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="theme-color" content="#00024A" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
        </Head>
        <div className={mainFontFamily.className}>   
            <IndexCP />
        </div>
    </div>

  )
}
