import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeaderB from '../components/Header_branco'
import MainFGTS from '../components/MainFGTS'
import Footer from '../components/Footer'
import Grid from '../components/Grid'
import Exec from '../components/Exercicios'

export default function Home() {
  return (
    
    <div className={styles.container}>

      <Head>
        <title>Antecipação Saque aniversário FGTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2&family=Dongle:wght@300&family=Poppins&family=Ubuntu:wght@300&display=swap" rel="stylesheet"></link>
        <script src="https://kit.fontawesome.com/8d9284e27b.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      </Head>

      <HeaderB/>
      <MainFGTS/>
      <Footer/>
           
    </div>

  )
}
